site_name: 咸鱼云网盘
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
#    - navigation.sections
#    - navigation.indexes
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - 用户手册:
    - 简介: index.md
    - 快速开始:
      - 运行部署: quick-start/index.md
      - 配置参数: quick-start/config.md
      - 关于前端: quick-start/front-end.md
      - 衍生项目: quick-start/other.md
    - 插件:
        - 插件系统说明: extension/index.md
        - 插件：ftp-server: extension/ftp-server.md
        - 插件：mp3-thumbnail: extension/mp3-thumbnail.md
        - 插件：hadoop-store: extension/hadoop-store.md
        - 插件：minio-store: extension/minio-store.md
        - 插件：samba-store: extension/samba-store.md
        - 插件：sftp-store: extension/sftp-store.md
        - 插件：ftp-store: extension/ftp-store.md
        - 插件：video-enhance: extension/video-enhance.md
        - 插件：quick-share: extension/quick-share.md
        - 插件：web-shell: extension/web-shell.md
        - 插件：network-tools: extension/network-tools.md
        - 插件：static-publish: extension/static-publish.md
  - 开发手册:
      - 简介: develop/index.md
      - 项目构建: develop/build.md
      - 系统架构:
          - 集群兼容: develop/framework/cluster.md
          - 异步任务: develop/framework/async-task.md
          - 定时任务: develop/framework/schedule.md