logging:
  level:
    org: warn
    com: warn
    com.xiaotao: info
    com.saltedfishcloud: info


sys:
  service:
    # MQ provider，默认 redis
    # 启用 sfc-ext-local-mq 插件时，可选local。使用local仅支持单 JVM 进程内消息语义
    mq-provider: redis
  store:
    # 压缩文件操作使用的文件编码格式，默认使用系统默认编码，Linux: UTF-8，Windows: GBK
    archive-encoding: gbk

    # 存储服务类型，可选local、minio（需要拓展）、hdfs（需要拓展）
    type: local

    # 各类资源根目录存储路径
    root: store

    # 公共网盘根目录路径
    public-root: public

    # minio存储配置
    minio:
      access-key: xyy
      secret-key: xyy123456
      bucket: xyy

    # hdfs存储配置
    hdfs:
      url: hdfs://localhost:9000
      root: /xyy2
      user: xiaotao
