# 用户自定义程序配置文件

server:
  port: 8087
spring:
  jpa:
    database: mysql
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false&serverTimezone=UTC
      username: ${DB_USER:root}
      password: ${DB_PASSWORD:test}
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:0}
#    password:

sys:
  common:
    # 注册邀请码
    reg-code: ${REG_CODE:114514}
  sync:
    # 自动同步间隔，单位分钟，-1表示关闭自动同步(该功能不稳定,不推荐使用同步和存储切换功能,建议一开始就确定好存储模式后不要再在管理员后台改动了)
    interval: -1

    # 咸鱼云启动时立即同步，默认关闭
    sync-on-launch: false
  store:
    # 压缩文件操作使用的文件编码格式，默认使用系统默认编码，Linux: UTF-8，Windows: GBK
    archive-encoding: gbk

    # 存储服务类型，可选hdfs（需要hdfs拓展）或local
    type: ${STORE_TYPE:local}

    # 各类资源根目录存储路径
    root: ${STORE_ROOT:store}

    # 公共网盘根目录路径
    public-root: ${PUBLIC_ROOT:public}

    # 存储模式，可选 raw - 原始存储 或 unique - 唯一存储
    # 注意:仅首次启动有效, 后续需要切换请在管理员后台切换, 但需要注意的是切换功能不是特别稳定, 容易导致数据丢失, 所以最好一开始就确定好存储模式不要再动了
    # (切换功能已经修过好几次严重bug了, 虽然目前没发现有bug, 但不确保真的没bug)
    mode: unique
  ftp:
    # FTP控制端口
    control-port: 21

    # FTP监听地址
    listen-addr: 0.0.0.0

    # 是否开启FTP
    ftp-enable: true

    # FTP被动模式传输重定向地址
    passive-addr: localhost

    # FTP被动模式传输端口范围
    passive-port: 20000-30000
