# 用户自定义程序配置文件

server:
  port: 8087
spring:
  jpa:
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${DB_HOST:127.0.0.1}/${DB_NAME:xyy}?${JDBC_PARAMETER:-useSSL=false&serverTimezone=UTC}"
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:test}
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:0}
#    password:

sys:
  service:
    # 缓存provider，默认 redis，可选 local（程序内缓存）
    cache-provider: redis
    # MQ provider，默认 redis
    # 启用 sfc-ext-local-mq 插件时，可选local。使用local仅支持单 JVM 进程内消息语义
    mq-provider: redis
    local-mq:
      # 本地消息队列的历史消息记录最长长度，默认为 4096。过大的值可能会导致OOM
      max-queue-size: 4096
      # 淘汰目标比例，消息数超出 max-queue-size 时淘汰至 max-queue-size * evict-target-ratio，默认 0.85
      evict-target-ratio: 0.85
  store:
    # 压缩文件操作使用的文件编码格式，默认使用系统默认编码，Linux: UTF-8，Windows: GBK
    archive-encoding: ${ARCHIVE_ENCODING:}

    # 存储服务类型，可选hdfs（需要hdfs拓展）或local
    type: ${STORE_TYPE:local}

    # 除公共网盘外，各类资源根目录存储路径（缩略图、缓存、临时文件、私人网盘数据、用户头像、按哈希组织的文件集合等数据）
    root: ${STORE_ROOT:store}

    # 单独的公共网盘根目录路径
    # 仅在 管理员后台-系统-基础配置-存储模式 设置为 UNIQUE(默认) 时有效。（注：切换存储模式会触发全网盘数据重新组织，中途出错可能会导致数据丢失和损坏，请谨慎切换并做好数据备份）
    public-root: ${PUBLIC_ROOT:public}

    # minio存储配置
    # 安装了 sfc-ext-minio-store 插件后，sys.store.type设置为minio后生效
    minio:
      access-key: ${MINIO_ACCESS_KEY:xyy}
      secret-key: ${MINIO_SECRET_KEY:xyy123456}
      bucket: ${MINIO_BUCKET:xyy}

    # hdfs存储配置
    # 安装了 sfc-ext-hadoop-store 插件后，sys.store.type设置为hdfs后生效
    # 注意：该插件未在jdk25中进行测试，使用时请确保hadoop版本和jdk版本兼容，且hadoop环境配置正确，否则可能会导致程序无法启动或运行时异常
    hdfs:
      url: ${HDFS_URL:hdfs://localhost:9000}
      root: ${HDFS_ROOT:/xyy2}
      user: ${HDFS_USER:xiaotao}
